In [1]:
s = "Hi there Sam!"

x = s.split()

print(x)

['Hi', 'there', 'Sam!']


In [2]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [5]:
import numpy as np

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
import numpy as np
array=np.arange(20,36)
print("Array of the integers from 20 to 35")
print(array)

Array of the integers from 20 to 35
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [9]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
c = np.concatenate((a, b), axis=0)
print(c)

[1 2 3 4 5 6]


In [12]:
import pandas as pd

In [13]:

data = [10,20,30]

In [15]:
df = pd.DataFrame(data, columns=['Numbers'])

In [ ]:
print(df)

In [17]:
pd.date_range(start='1/1/2023', end='10/02/2023', freq='M')

DatetimeIndex(['2023-01-31', '2023-02-28', '2023-03-31', '2023-04-30',
               '2023-05-31', '2023-06-30', '2023-07-31', '2023-08-31',
               '2023-09-30'],
              dtype='datetime64[ns]', freq='M')

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
print(type(a))

for b in lists:
    for j in b:
        print(j)

dt=zip(lists)
df=pd.DataFrame(dt,columns=["d"])
print(type(df))
print(df)

<class 'numpy.ndarray'>
1
aaa
22
2
bbb
25
3
ccc
24
<class 'pandas.core.frame.DataFrame'>
              d
0  [1, aaa, 22]
1  [2, bbb, 25]
2  [3, ccc, 24]
